# Generated by Django 2.1.4 on 2018-12-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ParamsSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.ManyToManyField(blank=True, related_name='param_in_set', to='core.Param')),
            ],
        ),
        migrations.CreateModel(
            name='QuestLeaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'question'), ('2', 'leaf')], default='2', max_length=1)),
                ('text', models.TextField()),
                ('next', models.ManyToManyField(blank=True, related_name='next_leaf', to='core.QuestLeaf')),
                ('params', models.ManyToManyField(blank=True, related_name='leaf_param', to='core.Param')),
                ('raise_param', models.ManyToManyField(blank=True, related_name='leaf_raise', to='core.Param')),
            ],
        ),
    ]
