# Generated by Django 2.2 on 2019-04-03 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='person',
        ),
    ]
