# Generated by Django 2.2 on 2019-04-03 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_remove_table_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='person_in_table', to='core.Table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='table_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
