# Generated by Django 2.2 on 2019-04-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20190403_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='table',
        ),
        migrations.AddField(
            model_name='table',
            name='persons',
            field=models.ManyToManyField(related_name='table_person', to='core.Person'),
        ),
    ]
